import '../config.dart';

class AppArray {
  // On boarding list
  var onBoardingList = [
    {
      "image": eImageAssets.ob1,
      "title": appFonts.chatWith,
      "subtitle": appFonts.openAiChatGpt
    },
    {
      "image": eImageAssets.ob2,
      "title": appFonts.easilyGenerateImage,
      "subtitle": appFonts.toReceiveTheFinest
    },
    {
      "image": eImageAssets.ob3,
      "title": appFonts.quickCreation,
      "subtitle": appFonts.enterTheTitle
    }
  ];

//Select character list
  var selectCharacterList = [
    {"image": eImageAssets.sc1, "title": appFonts.dino},
    {"image": eImageAssets.sc2, "title": appFonts.king},
    {"image": eImageAssets.sc3, "title": appFonts.dolly},
    {"image": eImageAssets.sc4, "title": appFonts.kettie},
    {"image": eImageAssets.sc5, "title": appFonts.marvel},
    {"image": eImageAssets.sc6, "title": appFonts.henny},
    {"image": eImageAssets.sc7, "title": appFonts.sophie}
  ];

// Languages list
  var languagesList = [
    {
      "image": eImageAssets.english,
      "title": appFonts.english,
      'locale': const Locale('en', 'US'),
      "code": "en"
    },
    {
      "image": eImageAssets.indian,
      "title": appFonts.hindi,
      'locale': const Locale('hi', 'IN'),
      "code": "hi"
    },
    {
      "image": eImageAssets.french,
      "title": appFonts.french,
      'locale': const Locale('fr', 'CA'),
      "code": "fr"
    },
    {
      "image": eImageAssets.italian,
      "title": appFonts.italian,
      'locale': const Locale('it', 'IT'),
      "code": "it"
    },
    {
      "image": eImageAssets.german,
      "title": appFonts.german,
      'locale': const Locale('ge', 'GE'),
      "code": "ge"
    },
    {
      "image": eImageAssets.japanese,
      "title": appFonts.japanese,
      'locale': const Locale('ja', 'JP'),
      "code": "ja"
    },
  ];

  // bottom list
  var bottomList = [
    {
      "title": "home",
      "icon": eSvgAssets.home,
      "iconSelected": eSvgAssets.homeColor
    },
    {
      "title": "chat",
      "icon": eSvgAssets.chat,
      "iconSelected": eSvgAssets.chatColor
    },
    {
      "title": "image",
      "icon": eSvgAssets.gallery,
      "iconSelected": eSvgAssets.galleryColor
    },
    {
      "title": "content",
      "icon": eSvgAssets.content,
      "iconSelected": eSvgAssets.contentColor
    },
    {
      "title": "setting",
      "icon": eSvgAssets.setting,
      "iconSelected": eSvgAssets.settingColor
    }
  ];

  // homeOption list
  var homeOptionList = [
    {"title": "option1", "icon": eSvgAssets.chatColor, "desc": "desc1"},
    {"title": "option2", "icon": eSvgAssets.galleryColor, "desc": "desc2"},
    {"title": "option3", "icon": eSvgAssets.contentColor, "desc": "desc3"}
  ];

  //drawer list
  var drawerList = [
    {"title": "chatBot", "icon": eSvgAssets.chat},
    {"title": "chatHistory", "icon": eSvgAssets.chatHistory},
    {"title": "option2", "icon": eSvgAssets.gallery},
    {"title": "option3", "icon": eSvgAssets.content},
    {"title": "setting", "icon": eSvgAssets.setting},
  ];

  // notification list
  var notificationsList = [
    {
      "image": eImageAssets.sc6,
      "title": appFonts.hennyHasSent,
      "subtitle": appFonts.justNow,
    },
    {
      "image": eImageAssets.lock,
      "title": appFonts.yourPasswordHasBeen,
      "subtitle": appFonts.am12,
    },
    {
      "image": eImageAssets.sc7,
      "title": appFonts.sophieHasWrite,
      "subtitle": appFonts.am11,
    },
    {
      "image": eImageAssets.sc1,
      "title": appFonts.dinoHasSent,
      "subtitle": appFonts.am10,
    },
    {
      "image": eImageAssets.sc5,
      "title": appFonts.marvelHasSent,
      "subtitle": appFonts.am9,
    },
    {
      "image": eImageAssets.sc4,
      "title": appFonts.kettieHasWrite,
      "subtitle": appFonts.am9,
    },
    {
      "image": eImageAssets.sc2,
      "title": appFonts.kingHasSend,
      "subtitle": appFonts.am9,
    },
  ];

// image size list
  var imageSizeList = ['256x256', '512x512', '1024x1024'];

  // view type list
  var viewTypeList = [appFonts.pageType, appFonts.gridType];

  // images list of image generator
  var imageGeneratorList = [
    {"image": eImageAssets.ig1},
    {"image": eImageAssets.ig2},
    {"image": eImageAssets.ig3},
    {"image": eImageAssets.ig4},
    {"image": eImageAssets.ig5},
    {"image": eImageAssets.ig6},
  ];

// no. of images list
  var noOfImagesList = ["5", "10", "15", "20"];

// image style list
  var imageStyleList = [
    appFonts.defaults,
    appFonts.abstract,
    appFonts.anime,
    appFonts.cartoon,
    appFonts.comic
  ];

// mood list
  var moodList = [
    appFonts.defaults,
    appFonts.happy,
    appFonts.sad,
    appFonts.angry
  ];

// image color list
  var imageColorList = [
    appFonts.defaults,
    appFonts.color,
    appFonts.blackWhite,
    appFonts.neon
  ];

  //background list
  var backgroundList = [
    {"image": eImageAssets.background1, "darkImage": eImageAssets.dBg1},
    {"image": eImageAssets.background2, "darkImage": eImageAssets.dBg2},
    {"image": eImageAssets.background3, "darkImage": eImageAssets.dBg3},
    {"image": eImageAssets.background4, "darkImage": eImageAssets.dBg4},
    {"image": eImageAssets.background5, "darkImage": eImageAssets.dBg5},
    {"image": eImageAssets.background6, "darkImage": eImageAssets.dBg6}
  ];

  //setting list
  var settingList = [
    {"icon": eSvgAssets.profile, "title": "myAccount"},
    {"icon": eSvgAssets.selectCharacter, "title": "selectCharacter"},
    {"icon": eSvgAssets.rtl, "title": "rtl"},
    {"icon": eSvgAssets.fingerLock, "title": "fingerprintLock"},
    {"icon": eSvgAssets.apiKey, "title": "manageApiKey"},
    {"icon": eSvgAssets.translate, "title": "language"},
    {"icon": eSvgAssets.star, "title": "rateApp"},
    {"icon": eSvgAssets.share, "title": "shareApp"},
    {"icon": eSvgAssets.security, "title": "privacyTerm"},
    {"icon": eSvgAssets.refund, "title": "refundPolicy"},
    {"icon": eSvgAssets.logout, "title": "logout"}
  ];

  //content option List
  var contentOptionList = [
    "businessIdea",
    "coverLetter",
    "blogSection",
    "marketingWriting",
    "service"
  ];

  // notification list
  var notificationList = [
    {
      "title": appFonts.newMessage,
      "value": true,
    },
    {
      "title": appFonts.newUpdates,
      "value": false,
    },
    {
      "title": appFonts.passwordChange,
      "value": true,
    },
  ];


// chat history
  var chatHistoryList = [
    {
      "icon": eImageAssets.sc1,
      "title": appFonts.whatIsApp,
      "subtitle": appFonts.min2,
    },
    {
      "icon": eImageAssets.sc2,
      "title": appFonts.howToMake,
      "subtitle": appFonts.min50,
    },
    {
      "icon": eImageAssets.sc3,
      "title": appFonts.whatIsTheNext,
      "subtitle": appFonts.yesterday,
    },
    {
      "icon": eImageAssets.sc4,
      "title": appFonts.whoIsShahRukh,
      "subtitle": appFonts.march26,
    },
    {
      "icon": eImageAssets.sc5,
      "title": appFonts.howTolLearn,
      "subtitle": appFonts.march25,
    },
    {
      "icon": eImageAssets.sc6,
      "title": appFonts.isACourse,
      "subtitle": appFonts.march24,
    },
    {
      "icon": eImageAssets.sc7,
      "title": appFonts.whatIsFull,
      "subtitle": appFonts.march23,
    },
  ];

  var paymentMethodList = [
    {
      "icon": eImageAssets.paypal,
      "title": appFonts.payPal
    },
    {
      "icon": eImageAssets.stripe,
      "title": appFonts.stripe
    },
    {"icon": eImageAssets.razor, "title": appFonts.razor},
    {"icon": eImageAssets.inApp, "title": appFonts.inApp},
    {"icon": eImageAssets.flutterWave, "title": appFonts.flutterWave},
    {"icon": eImageAssets.paystack, "title": appFonts.payStack},
  ];

  var quickAdvisor = [

    {"id": 0,"icon": eSvgAssets.askAnything, "title": appFonts.askAnything},
    {"id": 1,"icon": eSvgAssets.codeGenerator, "title": appFonts.codeGenerator},
    {"id": 2,"icon": eSvgAssets.translateAnything, "title": appFonts.translateAnything},
    {"id": 3,"icon": eSvgAssets.socialMedia, "title": appFonts.socialMedia},
    {"id": 4,"icon": eSvgAssets.emailGenerator, "title": appFonts.emailGenerator},
    {"id": 5,"icon": eSvgAssets.personalAdvice, "title": appFonts.personalAdvice},
    {"id": 6,"icon": eSvgAssets.passwordGenerator, "title": appFonts.passwordGenerator},
    {"id": 7,"icon": eSvgAssets.travel, "title": appFonts.travelHangout},
    {"id": 8,"icon": eSvgAssets.essay, "title": appFonts.essayWriter},
    {"id": 9,"icon": eSvgAssets.contentWriting, "title": appFonts.content1},
  /*  {"id": 10,"icon": eSvgAssets.ecommerce, "title": appFonts.ecommerceDetail},
    {"id": 11,"icon": eSvgAssets.asoExpert, "title": appFonts.asoExpert},
    {"id": 12,"icon": eSvgAssets.marketing, "title": appFonts.marketingAds}*/

  ];

  var translateLanguages = [
    'Abkhaz',
    'Afar',
    'Afrikaans',
    'Akan',
    'Albanian',
    'Amharic',
    'Arabic',
    'Aragonese',
    'Armenian',
    'Assamese',
    'Avaric',
    'Avestan',
    'Aymara',
    'Azerbaijani',
    'Bambara',
    'Bashkir',
    'Basque',
    'Belarusian',
    'Bengali',
    'Bihari',
    'Bislama',
    'Bosnian',
    'Breton',
    'Bulgarian',
    'Burmese',
    'Catalan',
    'Chamorro',
    'Chechen',
    'Chichewa',
    'Chinese',
    'Chuvash',
    'Cornish',
    'Corsican',
    'Cree',
    'Croatian',
    'Czech',
    'Danish',
    'Divehi',
    'Dutch',
    'English',
    'Esperanto',
    'Estonian',
    'Ewe',
    'Faroese',
    'Fijian',
    'Finnish',
    'French',
    'Fula',
    'Galician',
    'Georgian',
    'German',
    'Greek',
    'Guaraní',
    'Gujarati',
    'Haitian',
    'Hausa',
    'Hebrew',
    'Herero',
    'Hindi',
    'Hiri Motu',
    'Hungarian',
    'Interlingua',
    'Indonesian',
    'Interlingue',
    'Irish',
    'Igbo',
    'Inupiaq',
    'Ido',
    'Icelandic',
    'Italian',
    'Inuktitut',
    'Japanese',
    'Javanese',
    'Kalaallisut',
    'Kannada',
    'Kanuri',
    'Kashmiri',
    'Kazakh',
    'Khmer',
    'Kikuyu',
    'Kinyarwanda',
    'Kirghiz',
    'Komi',
    'Kongo',
    'Korean',
    'Kurdish',
    'Kwanyama',
    'Latin',
    'Luxembourgish',
    'Luganda',
    'Limburgish',
    'Lingala',
    'Lao',
    'Lithuanian',
    'Luba-Katanga',
    'Latvian',
    'Manx',
    'Macedonian',
    'Malagasy',
    'Malay',
    'Malayalam',
    'Maltese',
    'Māori',
    'Marathi',
    'Marshallese',
    'Mongolian',
    'Nauru',
    'Navajo',
    'Norwegian Bokmål',
    'North Ndebele',
    'Nepali',
    'Ndonga',
    'Norwegian Nynorsk',
    'Norwegian',
    'Nuosu',
    'South Ndebele',
    'Occitan',
    'Ojibwe',
    'Old Church Slavonic',
    'Oromo',
    'Oriya',
    'Ossetian',
    'Panjabi',
    'Pāli',
    'Persian',
    'Polish',
    'Pashto',
    'Portuguese',
    'Quechua',
    'Romansh',
    'Kirundi',
    'Romanian',
    'Russian',
    'Sanskrit',
    'Sardinian',
    'Sindhi',
    'Northern Sami',
    'Samoan',
    'Sango',
    'Serbian',
    'Scottish Gaelic',
    'Shona',
    'Sinhala',
    'Slovak',
    'Slovene',
    'Somali',
    'Southern Sotho',
    'Spanish',
    'Sundanese',
    'Swahili',
    'Swati',
    'Swedish',
    'Tamil',
    'Telugu',
    'Tajik',
    'Thai',
    'Tigrinya',
    'Tibetan',
    'Turkmen',
    'Tagalog',
    'Tswana',
    'Tonga',
    'Turkish',
    'Tsonga',
    'Tatar',
    'Twi',
    'Tahitian',
    'Uighur',
    'Ukrainian',
    'Urdu',
    'Uzbek',
    'Venda',
    'Vietnamese',
    'Volapük',
    'Walloon',
    'Welsh',
    'Wolof',
    'Western Frisian',
    'Xhosa',
    'Yiddish',
    'Yoruba',
    'Zhuang'
  ];

  var toneList = [
    "business",
    "general",
    "academic",
    "casual",
  ];

  var mailLengthList = [
    "small",
    "medium",
    "large",
  ];

  var socialMediaList = [
    {"image": eSvgAssets.caption, "title": appFonts.captionAbout},
    {"image": eSvgAssets.music, "title": appFonts.getMusicSuggestion},
    {"image": eSvgAssets.hashtag, "title": appFonts.findTheBest},
  ];

  var captionCreatorList = [
    {"image": eSvgAssets.insta, "title": appFonts.insta},
    {"image": eSvgAssets.linkedin, "title": appFonts.linkedin},
    {"image": eSvgAssets.twitter, "title": appFonts.twitter},
    {"image": eSvgAssets.youtube, "title": appFonts.youtube},
    {"image": eSvgAssets.fb, "title": appFonts.fbHalf},

  ];

  var captionToneList = [
    {"image": eImageAssets.funny, "title": appFonts.funny},
    {"image": eImageAssets.sad, "title": appFonts.sad},
    {"image": eImageAssets.serious, "title": appFonts.serious},
    {"image": eImageAssets.informative, "title": appFonts.informative}
  ];

  var passwordTypeList = [
    "onlyCharacter",
    "characterAndNumber",
    "characterNumberSymbol",
  ];

  var passwordStrengthList = [
    "poor",
    "average",
    "strong",
  ];

  var essayTypeList = [
    "informative",
    "persuade",
    "analyze",
  ];

  var travelHangoutList = [
    {"image": eSvgAssets.nearby, "title": appFonts.nearbyPoints},
    {"image": eSvgAssets.distance, "title": appFonts.distanceAttraction},
  ];

  var personalAdvisorList = [
    {"image": eSvgAssets.babyName, "title": appFonts.babyNameSuggestion},
    {"image": eSvgAssets.cv, "title": appFonts.cvMaker},
    {"image": eSvgAssets.gift, "title": appFonts.giftSuggestion},
    {"image": eSvgAssets.birthday, "title": appFonts.birthdayMessage},
    {"image": eSvgAssets.anniversary, "title": appFonts.anniversaryMessage},
    {"image": eSvgAssets.wedding, "title": appFonts.weddingWishes},
    {"image": eSvgAssets.newBaby, "title": appFonts.newBabyWishes},
    {"image": eSvgAssets.getWell, "title": appFonts.getWellMessage},
    {"image": eSvgAssets.newYear, "title": appFonts.newYearWishes},
    {"image": eSvgAssets.valentine, "title": appFonts.valentineDay},
    {"image": eSvgAssets.mothersDay, "title": appFonts.mothersDayWishes},
    {"image": eSvgAssets.fathersDay, "title": appFonts.fathersDayWishes},
    {"image": eSvgAssets.promotion, "title": appFonts.promotionWishes},
    {"image": eSvgAssets.babyShower, "title": appFonts.babyShowerMessage},
    {"image": eSvgAssets.farewell, "title": appFonts.farewellMessage},
  ];
  var genderList = [
    {"image": eSvgAssets.girl, "title": appFonts.girl},
    {"image": eSvgAssets.boy, "title": appFonts.boy},
  ];

  var nameSuggestionList = [
    "zodiac",
    "letter",
  ];

  //zodiac list
  var zodiacList = [
    'Aries',
    'Taurus',
    'Gemini',
    'Cancer',
    'Leo',
    'Virgo',
    'Libra',
    'Scorpio',
    'Sagittarius',
    'Capricorn',
    'Aquarius',
    'Pisces'
  ];

  // top-up balance option
  var topUpBalanceOption = [
    {"icon": eSvgAssets.star1, "price": 15},
    {"icon": eSvgAssets.crown, "price": 35},
    {"icon": eSvgAssets.diamond, "price": 65},
    {"icon": eSvgAssets.dollar1, "price": 0}
  ];

  var questionSuggestionList = [
    {"id": 1, "title": appFonts.code},
    {"id": 2, "title": appFonts.translation},
    {"id": 3, "title": appFonts.socialMedia},
    {"id": 4, "title": appFonts.travel}
  ];

  var questionsList = [
    {
      "id": 1,
      "title": appFonts.code,
      "preBuildQuestions": [

        {"title": appFonts.developmentArchitecture},
        {"title": appFonts.helpMeFindMistakes},
        {"title": appFonts.iNeedToCreateARest},
      ]
    },
    {
      "id": 2,
      "title": appFonts.code,
      "preBuildQuestions": [

        {"title": appFonts.writingThisCode},
        {"title": appFonts.iNeedToCreateARest},
      ]
    },
    {
      "id": 3,
      "preBuildQuestions": [
        {"title": appFonts.developmentArchitecture},
        {"title": appFonts.helpMeFindMistakes},
        {"title": appFonts.writingThisCode},
      ]
    },
    {
      "id": 4,
      "preBuildQuestions": [
        {"title": appFonts.developmentArchitecture},
        {"title": appFonts.helpMeFindMistakes},
        {"title": appFonts.iNeedToCreateARest},
      ]
    }
  ];

  var historyTagList = [
    {"title":appFonts.all},
    {"title": appFonts.chat},
    {"title": appFonts.code},
    {"title": appFonts.image},
    {"title": appFonts.translation}
  ];

  var imageScannerList = [
    {
      "title": appFonts.scanFromCamera,
      "image": eSvgAssets.cameraColor
    },
    {
      "title": appFonts.uploadFromGallery,
      "image": eSvgAssets.galleryColor
    },
  ];

  var ecommerceList = [
    {
      "title": appFonts.amazonProductFeature,
      "image": eSvgAssets.ecommerce
    },{
      "title": appFonts.amazonProductListing,
      "image": eSvgAssets.productListing
    },{
      "title": appFonts.amazonProductReview,
      "image": eSvgAssets.fillStar
    },{
      "title": appFonts.amazonProductTitle,
      "image": eSvgAssets.productTitle
    },{
      "title": appFonts.onlineDesc,
      "image": eSvgAssets.essay
    },{
      "title": appFonts.productGen,
      "image": eSvgAssets.productGenerator
    },{
      "title": appFonts.reviewResponder,
      "image": eSvgAssets.reviewResponder
    },{
      "title": appFonts.productRoadmap,
      "image": eSvgAssets.productRoadmap
    },
  ];

  var cityList = [
    "Port Blair",
    "Faridabad",
    "Gurgaon",
    "Hisar",
    "Rohtak",
    "Panipat",
    "Karnal",
    "Sonipat",
    "Yamunanagar",
    "Panchkula",
    "Bhiwani",
    "Bahadurgarh",
    "Jind",
    "Sirsa",
    "Thanesar",
    "Kaithal",
    "Palwal",
    "Rewari",
    "Hansi",
    "Narnaul",
    "Fatehabad",
    "Gohana",
    "Tohana",
    "Narwana",
    "Mandi Dabwali",
    "Charkhi Dadri",
    "Shahbad",
    "Pehowa",
    "Samalkha",
    "Pinjore",
    "Ladwa",
    "Sohna",
    "Safidon",
    "Taraori",
    "Mahendragarh",
    "Ratia",
    "Rania",
    "Sarsod",
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Tiruppur",
    "Ranipet",
    "Nagercoil",
    "Thanjavur",
    "Vellore",
    "Kancheepuram",
    "Erode",
    "Tiruvannamalai",
    "Pollachi",
    "Rajapalayam",
    "Sivakasi",
    "Pudukkottai",
    "Neyveli (TS)",
    "Nagapattinam",
    "Viluppuram",
    "Tiruchengode",
    "Vaniyambadi",
    "Theni Allinagaram",
    "Udhagamandalam",
    "Aruppukkottai",
    "Paramakudi",
    "Arakkonam",
    "Virudhachalam",
    "Srivilliputhur",
    "Tindivanam",
    "Virudhunagar",
    "Karur",
    "Valparai",
    "Sankarankovil",
    "Tenkasi",
    "Palani",
    "Pattukkottai",
    "Tirupathur",
    "Ramanathapuram",
    "Udumalaipettai",
    "Gobichettipalayam",
    "Thiruvarur",
    "Thiruvallur",
    "Panruti",
    "Namakkal",
    "Thirumangalam",
    "Vikramasingapuram",
    "Nellikuppam",
    "Rasipuram",
    "Tiruttani",
    "Nandivaram-Guduvancheri",
    "Periyakulam",
    "Pernampattu",
    "Vellakoil",
    "Sivaganga",
    "Vadalur",
    "Rameshwaram",
    "Tiruvethipuram",
    "Perambalur",
    "Usilampatti",
    "Vedaranyam",
    "Sathyamangalam",
    "Puliyankudi",
    "Nanjikottai",
    "Thuraiyur",
    "Sirkali",
    "Tiruchendur",
    "Periyasemur",
    "Sattur",
    "Vandavasi",
    "Tharamangalam",
    "Tirukkoyilur",
    "Oddanchatram",
    "Palladam",
    "Vadakkuvalliyur",
    "Tirukalukundram",
    "Uthamapalayam",
    "Surandai",
    "Sankari",
    "Shenkottai",
    "Vadipatti",
    "Sholingur",
    "Tirupathur",
    "Manachanallur",
    "Viswanatham",
    "Polur",
    "Panagudi",
    "Uthiramerur",
    "Thiruthuraipoondi",
    "Pallapatti",
    "Ponneri",
    "Lalgudi",
    "Natham",
    "Unnamalaikadai",
    "P.N.Patti",
    "Tharangambadi",
    "Tittakudi",
    "Pacode",
    "O' Valley",
    "Suriyampalayam",
    "Sholavandan",
    "Thammampatti",
    "Namagiripettai",
    "Peravurani",
    "Parangipettai",
    "Pudupattinam",
    "Pallikonda",
    "Sivagiri",
    "Punjaipugalur",
    "Padmanabhapuram",
    "Thirupuvanam",
    "Indore",
    "Bhopal",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Ratlam",
    "Satna",
    "Murwara (Katni)",
    "Morena",
    "Singrauli",
    "Rewa",
    "Vidisha",
    "Ganjbasoda",
    "Shivpuri",
    "Mandsaur",
    "Neemuch",
    "Nagda",
    "Itarsi",
    "Sarni",
    "Sehore",
    "Mhow Cantonment",
    "Seoni",
    "Balaghat",
    "Ashok Nagar",
    "Tikamgarh",
    "Shahdol",
    "Pithampur",
    "Alirajpur",
    "Mandla",
    "Sheopur",
    "Shajapur",
    "Panna",
    "Raghogarh-Vijaypur",
    "Sendhwa",
    "Sidhi",
    "Pipariya",
    "Shujalpur",
    "Sironj",
    "Pandhurna",
    "Nowgong",
    "Mandideep",
    "Sihora",
    "Raisen",
    "Lahar",
    "Maihar",
    "Sanawad",
    "Sabalgarh",
    "Umaria",
    "Porsa",
    "Narsinghgarh",
    "Malaj Khand",
    "Sarangpur",
    "Mundi",
    "Nepanagar",
    "Pasan",
    "Mahidpur",
    "Seoni-Malwa",
    "Rehli",
    "Manawar",
    "Rahatgarh",
    "Panagar",
    "Wara Seoni",
    "Tarana",
    "Sausar",
    "Rajgarh",
    "Niwari",
    "Mauganj",
    "Manasa",
    "Nainpur",
    "Prithvipur",
    "Sohagpur",
    "Nowrozabad (Khodargama)",
    "Shamgarh",
    "Maharajpur",
    "Multai",
    "Pali",
    "Pachore",
    "Rau",
    "Mhowgaon",
    "Vijaypur",
    "Narsinghgarh",
    "Dhanbad",
    "Ranchi",
    "Jamshedpur",
    "Bokaro Steel City",
    "Deoghar",
    "Phusro",
    "Adityapur",
    "Hazaribag",
    "Giridih",
    "Ramgarh",
    "Jhumri Tilaiya",
    "Saunda",
    "Sahibganj",
    "Medininagar (Daltonganj)",
    "Chaibasa",
    "Chatra",
    "Gumia",
    "Dumka",
    "Madhupur",
    "Chirkunda",
    "Pakaur",
    "Simdega",
    "Musabani",
    "Mihijam",
    "Patratu",
    "Lohardaga",
    "Tenu dam-cum-Kathhara",
    "Aizawl",
    "Lunglei",
    "Saiha",
    "Dimapur",
    "Kohima",
    "Zunheboto",
    "Tuensang",
    "Wokha",
    "Mokokchung",
    "Shimla",
    "Mandi",
    "Solan",
    "Nahan",
    "Sundarnagar",
    "Palampur",
    "Kullu",
    "Agartala",
    "Udaipur",
    "Dharmanagar",
    "Pratapgarh",
    "Kailasahar",
    "Belonia",
    "Khowai",
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Rajahmundry",
    "Kakinada",
    "Tirupati",
    "Anantapur",
    "Kadapa",
    "Vizianagaram",
    "Eluru",
    "Ongole",
    "Nandyal",
    "Machilipatnam",
    "Adoni",
    "Tenali",
    "Chittoor",
    "Hindupur",
    "Proddatur",
    "Bhimavaram",
    "Madanapalle",
    "Guntakal",
    "Dharmavaram",
    "Gudivada",
    "Srikakulam",
    "Narasaraopet",
    "Rajampet",
    "Tadpatri",
    "Tadepalligudem",
    "Chilakaluripet",
    "Yemmiganur",
    "Kadiri",
    "Chirala",
    "Anakapalle",
    "Kavali",
    "Palacole",
    "Sullurpeta",
    "Tanuku",
    "Rayachoti",
    "Srikalahasti",
    "Bapatla",
    "Naidupet",
    "Nagari",
    "Gudur",
    "Vinukonda",
    "Narasapuram",
    "Nuzvid",
    "Markapur",
    "Ponnur",
    "Kandukur",
    "Bobbili",
    "Rayadurg",
    "Samalkot",
    "Jaggaiahpet",
    "Tuni",
    "Amalapuram",
    "Bheemunipatnam",
    "Venkatagiri",
    "Sattenapalle",
    "Pithapuram",
    "Palasa Kasibugga",
    "Parvathipuram",
    "Macherla",
    "Gooty",
    "Salur",
    "Mandapeta",
    "Jammalamadugu",
    "Peddapuram",
    "Punganur",
    "Nidadavole",
    "Repalle",
    "Ramachandrapuram",
    "Kovvur",
    "Tiruvuru",
    "Uravakonda",
    "Narsipatnam",
    "Yerraguntla",
    "Pedana",
    "Puttur",
    "Renigunta",
    "Rajam",
    "Ludhiana",
    "Patiala",
    "Amritsar",
    "Jalandhar",
    "Bathinda",
    "Pathankot",
    "Hoshiarpur",
    "Batala",
    "Moga",
    "Malerkotla",
    "Khanna",
    "Mohali",
    "Barnala",
    "Firozpur",
    "Phagwara",
    "Kapurthala",
    "Zirakpur",
    "Kot Kapura",
    "Faridkot",
    "Muktsar",
    "Rajpura",
    "Sangrur",
    "Fazilka",
    "Gurdaspur",
    "Kharar",
    "Gobindgarh",
    "Mansa",
    "Malout",
    "Nabha",
    "Tarn Taran",
    "Jagraon",
    "Sunam",
    "Dhuri",
    "Firozpur Cantt.",
    "Sirhind Fatehgarh Sahib",
    "Rupnagar",
    "Jalandhar Cantt.",
    "Samana",
    "Nawanshahr",
    "Rampura Phul",
    "Nangal",
    "Nakodar",
    "Zira",
    "Patti",
    "Raikot",
    "Longowal",
    "Urmar Tanda",
    "Morinda, India",
    "Phillaur",
    "Pattran",
    "Qadian",
    "Sujanpur",
    "Mukerian",
    "Talwara",
    "Chandigarh",
    "Jaipur",
    "Jodhpur",
    "Bikaner",
    "Udaipur",
    "Ajmer",
    "Bhilwara",
    "Alwar",
    "Bharatpur",
    "Pali",
    "Barmer",
    "Sikar",
    "Tonk",
    "Sadulpur",
    "Sawai Madhopur",
    "Nagaur",
    "Makrana",
    "Sujangarh",
    "Sardarshahar",
    "Ladnu",
    "Ratangarh",
    "Nokha",
    "Nimbahera",
    "Suratgarh",
    "Rajsamand",
    "Lachhmangarh",
    "Rajgarh (Churu)",
    "Nasirabad",
    "Nohar",
    "Phalodi",
    "Nathdwara",
    "Pilani",
    "Merta City",
    "Sojat",
    "Neem-Ka-Thana",
    "Sirohi",
    "Pratapgarh",
    "Rawatbhata",
    "Sangaria",
    "Lalsot",
    "Pilibanga",
    "Pipar City",
    "Taranagar",
    "Vijainagar, Ajmer",
    "Sumerpur",
    "Sagwara",
    "Ramganj Mandi",
    "Lakheri",
    "Udaipurwati",
    "Losal",
    "Sri Madhopur",
    "Ramngarh",
    "Rawatsar",
    "Rajakhera",
    "Shahpura",
    "Shahpura",
    "Raisinghnagar",
    "Malpura",
    "Nadbai",
    "Sanchore",
    "Nagar",
    "Rajgarh (Alwar)",
    "Sheoganj",
    "Sadri",
    "Todaraisingh",
    "Todabhim",
    "Reengus",
    "Rajaldesar",
    "Sadulshahar",
    "Sambhar",
    "Prantij",
    "Mount Abu",
    "Mangrol",
    "Phulera",
    "Mandawa",
    "Pindwara",
    "Mandalgarh",
    "Takhatgarh",
    "Guwahati",
    "Silchar",
    "Dibrugarh",
    "Nagaon",
    "Tinsukia",
    "Jorhat",
    "Bongaigaon City",
    "Dhubri",
    "Diphu",
    "North Lakhimpur",
    "Tezpur",
    "Karimganj",
    "Sibsagar",
    "Goalpara",
    "Barpeta",
    "Lanka",
    "Lumding",
    "Mankachar",
    "Nalbari",
    "Rangia",
    "Margherita",
    "Mangaldoi",
    "Silapathar",
    "Mariani",
    "Marigaon",
    "Bhubaneswar",
    "Cuttack",
    "Raurkela",
    "Brahmapur",
    "Sambalpur",
    "Puri",
    "Baleshwar Town",
    "Baripada Town",
    "Bhadrak",
    "Balangir",
    "Jharsuguda",
    "Bargarh",
    "Paradip",
    "Bhawanipatna",
    "Dhenkanal",
    "Barbil",
    "Kendujhar",
    "Sunabeda",
    "Rayagada",
    "Jatani",
    "Byasanagar",
    "Kendrapara",
    "Rajagangapur",
    "Parlakhemundi",
    "Talcher",
    "Sundargarh",
    "Phulabani",
    "Pattamundai",
    "Titlagarh",
    "Nabarangapur",
    "Soro",
    "Malkangiri",
    "Rairangpur",
    "Tarbha",
    "Raipur",
    "Bhilai Nagar",
    "Korba",
    "Bilaspur",
    "Durg",
    "Rajnandgaon",
    "Jagdalpur",
    "Raigarh",
    "Ambikapur",
    "Mahasamund",
    "Dhamtari",
    "Chirmiri",
    "Bhatapara",
    "Dalli-Rajhara",
    "Naila Janjgir",
    "Tilda Newra",
    "Mungeli",
    "Manendragarh",
    "Sakti",
    "Srinagar",
    "Jammu",
    "Baramula",
    "Anantnag",
    "Sopore",
    "KathUrban Agglomeration",
    "Rajauri",
    "Punch",
    "Udhampur",
    "Bengaluru",
    "Hubli-Dharwad",
    "Belagavi",
    "Mangaluru",
    "Davanagere",
    "Ballari",
    "Mysore",
    "Tumkur",
    "Shivamogga",
    "Raayachuru",
    "Robertson Pet",
    "Kolar",
    "Mandya",
    "Udupi",
    "Chikkamagaluru",
    "Karwar",
    "Ranebennuru",
    "Ranibennur",
    "Ramanagaram",
    "Gokak",
    "Yadgir",
    "Rabkavi Banhatti",
    "Shahabad",
    "Sirsi",
    "Sindhnur",
    "Tiptur",
    "Arsikere",
    "Nanjangud",
    "Sagara",
    "Sira",
    "Puttur",
    "Athni",
    "Mulbagal",
    "Surapura",
    "Siruguppa",
    "Mudhol",
    "Sidlaghatta",
    "Shahpur",
    "Saundatti-Yellamma",
    "Wadi",
    "Manvi",
    "Nelamangala",
    "Lakshmeshwar",
    "Ramdurg",
    "Nargund",
    "Tarikere",
    "Malavalli",
    "Savanur",
    "Lingsugur",
    "Vijayapura",
    "Sankeshwara",
    "Madikeri",
    "Talikota",
    "Sedam",
    "Shikaripur",
    "Mahalingapura",
    "Mudalagi",
    "Muddebihal",
    "Pavagada",
    "Malur",
    "Sindhagi",
    "Sanduru",
    "Afzalpur",
    "Maddur",
    "Madhugiri",
    "Tekkalakote",
    "Terdal",
    "Mudabidri",
    "Magadi",
    "Navalgund",
    "Shiggaon",
    "Shrirangapattana",
    "Sindagi",
    "Sakaleshapura",
    "Srinivaspur",
    "Ron",
    "Mundargi",
    "Sadalagi",
    "Piriyapatna",
    "Adyar",
    "Imphal",
    "Thoubal",
    "Lilong",
    "Mayang Imphal",
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Kollam",
    "Thrissur",
    "Palakkad",
    "Alappuzha",
    "Malappuram",
    "Ponnani",
    "Vatakara",
    "Kanhangad",
    "Taliparamba",
    "Koyilandy",
    "Neyyattinkara",
    "Kayamkulam",
    "Nedumangad",
    "Kannur",
    "Tirur",
    "Kottayam",
    "Kasaragod",
    "Kunnamkulam",
    "Ottappalam",
    "Thiruvalla",
    "Thodupuzha",
    "Chalakudy",
    "Changanassery",
    "Punalur",
    "Nilambur",
    "Cherthala",
    "Perinthalmanna",
    "Mattannur",
    "Shoranur",
    "Varkala",
    "Paravoor",
    "Pathanamthitta",
    "Peringathur",
    "Attingal",
    "Kodungallur",
    "Pappinisseri",
    "Chittur-Thathamangalam",
    "Muvattupuzha",
    "Adoor",
    "Mavelikkara",
    "Mavoor",
    "Perumbavoor",
    "Vaikom",
    "Palai",
    "Panniyannur",
    "Guruvayoor",
    "Puthuppally",
    "Panamattom",
    "Delhi",
    "New Delhi",
    "Silvassa",
    "Pondicherry",
    "Karaikal",
    "Yanam",
    "Mahe",
    "Dehradun",
    "Hardwar",
    "Haldwani-cum-Kathgodam",
    "Srinagar",
    "Kashipur",
    "Roorkee",
    "Rudrapur",
    "Rishikesh",
    "Ramnagar",
    "Pithoragarh",
    "Manglaur",
    "Nainital",
    "Mussoorie",
    "Tehri",
    "Pauri",
    "Nagla",
    "Sitarganj",
    "Bageshwar",
    "Lucknow",
    "Kanpur",
    "Firozabad",
    "Agra",
    "Meerut",
    "Varanasi",
    "Allahabad",
    "Amroha",
    "Moradabad",
    "Aligarh",
    "Saharanpur",
    "Noida",
    "Loni",
    "Jhansi",
    "Shahjahanpur",
    "Rampur",
    "Modinagar",
    "Hapur",
    "Etawah",
    "Sambhal",
    "Orai",
    "Bahraich",
    "Unnao",
    "Rae Bareli",
    "Lakhimpur",
    "Sitapur",
    "Lalitpur",
    "Pilibhit",
    "Chandausi",
    "Hardoi ",
    "Azamgarh",
    "Khair",
    "Sultanpur",
    "Tanda",
    "Nagina",
    "Shamli",
    "Najibabad",
    "Shikohabad",
    "Sikandrabad",
    "Shahabad, Hardoi",
    "Pilkhuwa",
    "Renukoot",
    "Vrindavan",
    "Ujhani",
    "Laharpur",
    "Tilhar",
    "Sahaswan",
    "Rath",
    "Sherkot",
    "Kalpi",
    "Tundla",
    "Sandila",
    "Nanpara",
    "Sardhana",
    "Nehtaur",
    "Seohara",
    "Padrauna",
    "Mathura",
    "Thakurdwara",
    "Nawabganj",
    "Siana",
    "Noorpur",
    "Sikandra Rao",
    "Puranpur",
    "Rudauli",
    "Thana Bhawan",
    "Palia Kalan",
    "Zaidpur",
    "Nautanwa",
    "Zamania",
    "Shikarpur, Bulandshahr",
    "Naugawan Sadat",
    "Fatehpur Sikri",
    "Shahabad, Rampur",
    "Robertsganj",
    "Utraula",
    "Sadabad",
    "Rasra",
    "Lar",
    "Lal Gopalganj Nindaura",
    "Sirsaganj",
    "Pihani",
    "Shamsabad, Agra",
    "Rudrapur",
    "Soron",
    "SUrban Agglomerationr",
    "Samdhan",
    "Sahjanwa",
    "Rampur Maniharan",
    "Sumerpur",
    "Shahganj",
    "Tulsipur",
    "Tirwaganj",
    "PurqUrban Agglomerationzi",
    "Shamsabad, Farrukhabad",
    "Warhapur",
    "Powayan",
    "Sandi",
    "Achhnera",
    "Naraura",
    "Nakur",
    "Sahaspur",
    "Safipur",
    "Reoti",
    "Sikanderpur",
    "Saidpur",
    "Sirsi",
    "Purwa",
    "Parasi",
    "Lalganj",
    "Phulpur",
    "Shishgarh",
    "Sahawar",
    "Samthar",
    "Pukhrayan",
    "Obra",
    "Niwai",
    "Mirzapur",
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Darbhanga",
    "Arrah",
    "Begusarai",
    "Chhapra",
    "Katihar",
    "Munger",
    "Purnia",
    "Saharsa",
    "Sasaram",
    "Hajipur",
    "Dehri-on-Sone",
    "Bettiah",
    "Motihari",
    "Bagaha",
    "Siwan",
    "Kishanganj",
    "Jamalpur",
    "Buxar",
    "Jehanabad",
    "Aurangabad",
    "Lakhisarai",
    "Nawada",
    "Jamui",
    "Sitamarhi",
    "Araria",
    "Gopalganj",
    "Madhubani",
    "Masaurhi",
    "Samastipur",
    "Mokameh",
    "Supaul",
    "Dumraon",
    "Arwal",
    "Forbesganj",
    "BhabUrban Agglomeration",
    "Narkatiaganj",
    "Naugachhia",
    "Madhepura",
    "Sheikhpura",
    "Sultanganj",
    "Raxaul Bazar",
    "Ramnagar",
    "Mahnar Bazar",
    "Warisaliganj",
    "Revelganj",
    "Rajgir",
    "Sonepur",
    "Sherghati",
    "Sugauli",
    "Makhdumpur",
    "Maner",
    "Rosera",
    "Nokha",
    "Piro",
    "Rafiganj",
    "Marhaura",
    "Mirganj",
    "Lalganj",
    "Murliganj",
    "Motipur",
    "Manihari",
    "Sheohar",
    "Maharajganj",
    "Silao",
    "Barh",
    "Asarganj",
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Nadiad",
    "Porbandar",
    "Anand",
    "Morvi",
    "Mahesana",
    "Bharuch",
    "Vapi",
    "Navsari",
    "Veraval",
    "Bhuj",
    "Godhra",
    "Palanpur",
    "Valsad",
    "Patan",
    "Deesa",
    "Amreli",
    "Anjar",
    "Dhoraji",
    "Khambhat",
    "Mahuva",
    "Keshod",
    "Wadhwan",
    "Ankleshwar",
    "Savarkundla",
    "Kadi",
    "Visnagar",
    "Upleta",
    "Una",
    "Sidhpur",
    "Unjha",
    "Mangrol",
    "Viramgam",
    "Modasa",
    "Palitana",
    "Petlad",
    "Kapadvanj",
    "Sihor",
    "Wankaner",
    "Limbdi",
    "Mandvi",
    "Thangadh",
    "Vyara",
    "Padra",
    "Lunawada",
    "Rajpipla",
    "Vapi",
    "Umreth",
    "Sanand",
    "Rajula",
    "Radhanpur",
    "Mahemdabad",
    "Ranavav",
    "Tharad",
    "Mansa",
    "Umbergaon",
    "Talaja",
    "Vadnagar",
    "Manavadar",
    "Salaya",
    "Vijapur",
    "Pardi",
    "Rapar",
    "Songadh",
    "Lathi",
    "Adalaj",
    "Chhapra",
    "Gandhinagar",
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Ramagundam",
    "Khammam",
    "Mahbubnagar",
    "Mancherial",
    "Adilabad",
    "Suryapet",
    "Jagtial",
    "Miryalaguda",
    "Nirmal",
    "Kamareddy",
    "Kothagudem",
    "Bodhan",
    "Palwancha",
    "Mandamarri",
    "Koratla",
    "Sircilla",
    "Tandur",
    "Siddipet",
    "Wanaparthy",
    "Kagaznagar",
    "Gadwal",
    "Sangareddy",
    "Bellampalle",
    "Bhongir",
    "Vikarabad",
    "Jangaon",
    "Bhadrachalam",
    "Bhainsa",
    "Farooqnagar",
    "Medak",
    "Narayanpet",
    "Sadasivpet",
    "Yellandu",
    "Manuguru",
    "Kyathampalle",
    "Nagarkurnool",
    "Shillong",
    "Tura",
    "Nongstoin",
    "Manali",
    "Naharlagun",
    "Pasighat",
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Nashik",
    "Kalyan-Dombivali",
    "Vasai-Virar",
    "Solapur",
    "Mira-Bhayandar",
    "Bhiwandi",
    "Amravati",
    "Nanded-Waghala",
    "Sangli",
    "Malegaon",
    "Akola",
    "Latur",
    "Dhule",
    "Ahmednagar",
    "Ichalkaranji",
    "Parbhani",
    "Panvel",
    "Yavatmal",
    "Achalpur",
    "Osmanabad",
    "Nandurbar",
    "Satara",
    "Wardha",
    "Udgir",
    "Aurangabad",
    "Amalner",
    "Akot",
    "Pandharpur",
    "Shrirampur",
    "Parli",
    "Washim",
    "Ambejogai",
    "Manmad",
    "Ratnagiri",
    "Uran Islampur",
    "Pusad",
    "Sangamner",
    "Shirpur-Warwade",
    "Malkapur",
    "Wani",
    "Lonavla",
    "Talegaon Dabhade",
    "Anjangaon",
    "Umred",
    "Palghar",
    "Shegaon",
    "Ozar",
    "Phaltan",
    "Yevla",
    "Shahade",
    "Vita",
    "Umarkhed",
    "Warora",
    "Pachora",
    "Tumsar",
    "Manjlegaon",
    "Sillod",
    "Arvi",
    "Nandura",
    "Vaijapur",
    "Wadgaon Road",
    "Sailu",
    "Murtijapur",
    "Tasgaon",
    "Mehkar",
    "Yawal",
    "Pulgaon",
    "Nilanga",
    "Wai",
    "Umarga",
    "Paithan",
    "Rahuri",
    "Nawapur",
    "Tuljapur",
    "Morshi",
    "Purna",
    "Satana",
    "Pathri",
    "Sinnar",
    "Uchgaon",
    "Uran",
    "Pen",
    "Karjat",
    "Manwath",
    "Partur",
    "Sangole",
    "Mangrulpir",
    "Risod",
    "Shirur",
    "Savner",
    "Sasvad",
    "Pandharkaoda",
    "Talode",
    "Shrigonda",
    "Shirdi",
    "Raver",
    "Mukhed",
    "Rajura",
    "Vadgaon Kasba",
    "Tirora",
    "Mahad",
    "Lonar",
    "Sawantwadi",
    "Pathardi",
    "Pauni",
    "Ramtek",
    "Mul",
    "Soyagaon",
    "Mangalvedhe",
    "Narkhed",
    "Shendurjana",
    "Patur",
    "Mhaswad",
    "Loha",
    "Nandgaon",
    "Warud",
    "Marmagao",
    "Panaji",
    "Margao",
    "Mapusa",
    "Kolkata",
    "Siliguri",
    "Asansol",
    "Raghunathganj",
    "Kharagpur",
    "Naihati",
    "English Bazar",
    "Baharampur",
    "Hugli-Chinsurah",
    "Raiganj",
    "Jalpaiguri",
    "Santipur",
    "Balurghat",
    "Medinipur",
    "Habra",
    "Ranaghat",
    "Bankura",
    "Nabadwip",
    "Darjiling",
    "Purulia",
    "Arambagh",
    "Tamluk",
    "AlipurdUrban Agglomerationr",
    "Suri",
    "Jhargram",
    "Gangarampur",
    "Rampurhat",
    "Kalimpong",
    "Sainthia",
    "Taki",
    "Murshidabad",
    "Memari",
    "Paschim Punropara",
    "Tarakeswar",
    "Sonamukhi",
    "PandUrban Agglomeration",
    "Mainaguri",
    "Malda",
    "Panchla",
    "Raghunathpur",
    "Mathabhanga",
    "Monoharpur",
    "Srirampore",
    "Adra"
  ];

  var placeList = [
    "Hotels",
    "Things to do",
    "Hill station",
    "Restaurant",
    "Museums",
    "Transit",
    "Pharmacies"
  ];

  var apiNoteList = [
    {
      "title": appFonts.note,
      "note": [
        {'title':appFonts.yourMobileDevices},
        {'title':appFonts.youCanKeep},
        {'title':appFonts.balanceNote}
      ]
    }
  ];

  var topUpPaymentList = [
    {
      "icon": eImageAssets.paypal,
      "title": appFonts.payPal
    },
    {
      "icon": eImageAssets.stripe,
      "title": appFonts.stripe
    },
    {"icon": eImageAssets.razor, "title": appFonts.razor},
    {"icon": eImageAssets.inApp, "title": appFonts.inApp},
    {"icon": eImageAssets.flutterWave, "title": appFonts.flutterWave},
    {"icon": eImageAssets.paystack, "title": appFonts.payStack},
  ];

}